version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 2431999
      MYSQL_USER: tiendung
      MYSQL_PASSWORD: 2431999
      MYSQL_DATABASE: itlearn5
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./data-volume:/var/lib/mysql
    networks:
      - api_network
  api:
    build: .
    image: itlearn_docker_image
    container_name: itlearn_docker_container
    restart: unless-stopped
    ports:
      - "9999:8000"
    networks:
      - api_network
    depends_on:
      - db
networks:
  api_network:
    driver: bridge