# Generated by Django 3.2.8 on 2021-11-08 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comment_parent_comment1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True, 'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='published',
            new_name='created',
        ),
        migrations.AddField(
            model_name='comment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='down_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='number_bookmarked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
