# Generated by Django 3.2.8 on 2021-11-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211112_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number_posts', models.IntegerField(default=0)),
                ('questions', models.ManyToManyField(blank=True, null=True, related_name='tags', to='app.Question')),
            ],
        ),
    ]
