# Generated by Django 3.2.8 on 2021-11-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211119_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number_post',
            field=models.IntegerField(default=0),
        ),
    ]
