# Generated by Django 3.2.8 on 2021-11-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_category_number_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='number_post',
        ),
    ]
