# Generated by Django 3.2.8 on 2021-11-26 02:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_remove_category_number_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='followed',
            field=models.ManyToManyField(related_name='follow_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
