# Generated by Django 3.2.8 on 2021-12-05 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20211204_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='followed',
            field=models.ManyToManyField(related_name='follow_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
