# Generated by Django 3.2.8 on 2021-11-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='authuser',
            name='use_full_comment',
            field=models.IntegerField(default=0),
        ),
    ]
