# Generated by Django 3.2.8 on 2022-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211227_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
